### ISSUE TITLE
calling python3 just opens the bash shell

### ISSUE THREAD

**Issue by slavekrouta** [AaronWatson2975/AndroidPython3#2]
I followed the guide so I copied the "python3" file to /system/bin/ and the whole "python3.4.2" folder to /system/ and set the permissions to 755, owner to root and group to shell, but calling the python3 executable just opens the default shell.

**Comment by slavekrouta** [comment]
### i needed to change the shebang and shell in the executable because of mine system modifications. Now, it works

**Comment by Exanoff12** [comment]
explain what and where you changed
